# -*- coding: utf-8 -*-

Celebration.create(day: 1, month: 1, description: "Confraternização Universal")
Celebration.create(day: 1, month: 1, description: "Dia Mundial da Paz")
Celebration.create(day: 1, month: 1, description: "Ano novo")
Celebration.create(day: 9, month: 1, description: "Dia do fico")
Celebration.create(day: 12, month: 1, description: "Aniversário da cidade de Belém do Pará")
Celebration.create(day: 13, month: 1, description: "Dia Nacional dos Indios")
Celebration.create(day: 20, month: 1, description: "Dia do Farmacêutico")
Celebration.create(day: 25, month: 1, description: "Aniversário da cidade de São Paulo")
Celebration.create(day: 30, month: 1, description: "Dia da história em quadrinhos")

Celebration.create(day: 1, month: 2, description: "Ratificação de todas as formas de discriminação contra a mulher")
Celebration.create(day: 1, month: 2, description: "Dia do Publicitário")
Celebration.create(day: 7, month: 2, description: "Dia do Gráfico")
Celebration.create(day: 19, month: 2, description: "Dia do esporte")
Celebration.create(day: 24, month: 2, description: "Dia da conquista do Voto feminino no Brasil")
Celebration.create(day: 27, month: 2, description: "Dia Nacional do Livro Didático")
Celebration.create(day: 27, month: 2, description: "Dia do Idoso")

Celebration.create(day: 1, month: 3, description: "Dia da fundação da Cidade do Rio de Janeiro")
Celebration.create(day: 2, month: 3, description: "Dia Nacional do Turismo")
Celebration.create(day: 2, month: 3, description: "Dia da Oração")
Celebration.create(day: 3, month: 3, description: "Dia do Meteorologista")
Celebration.create(day: 5, month: 3, description: "Dia do Filatelista Brasileiro")
Celebration.create(day: 7, month: 3, description: "Dia dos Fuzileiros Navais")
Celebration.create(day: 8, month: 3, description: "Dia Internacional da Mulher")
Celebration.create(day: 10, month: 3, description: "Dia do Telefone")
Celebration.create(day: 10, month: 3, description: "Dia do Sogro")
Celebration.create(day: 12, month: 3, description: "Aniversário de Recife e Olinda")
Celebration.create(day: 12, month: 3, description: "Dia do Bibliotecário")
Celebration.create(day: 14, month: 3, description: "Dia dos carecas")
Celebration.create(day: 14, month: 3, description: "Dia do Vendedor de Livros")
Celebration.create(day: 14, month: 3, description: "Dia Nacional da Poesia")
Celebration.create(day: 15, month: 3, description: "Dia da Escola")
Celebration.create(day: 15, month: 3, description: "Dia Mundial do Consumidor")
Celebration.create(day: 18, month: 3, description: "Dia do DeMolay")
Celebration.create(day: 19, month: 3, description: "Dia do Carpinteiro")
Celebration.create(day: 19, month: 3, description: "Dia do Marceneiro")
Celebration.create(day: 21, month: 3, description: "Início do Outono")
Celebration.create(day: 21, month: 3, description: "Dia mundial da Terra")
Celebration.create(day: 21, month: 3, description: "Dia Internacional Contra a Discriminação Racial")
Celebration.create(day: 21, month: 3, description: "Dia Universal do Teatro")
Celebration.create(day: 22, month: 3, description: "Dia Mundial da Água")
Celebration.create(day: 23, month: 3, description: "Dia Mundial do Optometrista")
Celebration.create(day: 23, month: 3, description: "Dia Mundial da Meteorologia")
Celebration.create(day: 25, month: 3, description: "Dia Nacional do Orgulho Gay")
Celebration.create(day: 26, month: 3, description: "Aniversário de Porto Alegre (Capital do Gaúchos)")
Celebration.create(day: 26, month: 3, description: "Dia do Cacau")
Celebration.create(day: 27, month: 3, description: "Dia do Circo")
Celebration.create(day: 28, month: 3, description: "Dia do Diagramador")
Celebration.create(day: 28, month: 3, description: "Dia do Revisor")
Celebration.create(day: 29, month: 3, description: "Dia da fundação da cidade de Salvador")
Celebration.create(day: 30, month: 3, description: "Dia Mundial da Juventude")
Celebration.create(day: 31, month: 3, description: "Dia da Integração Nacional")
Celebration.create(day: 31, month: 3, description: "Dia da Saúde e Nutrição")

Celebration.create(day: 1, month: 4, description: "Aniversário do Golpe Militar - 1964")
Celebration.create(day: 1, month: 4, description: "Dia da Mentira")
Celebration.create(day: 1, month: 4, description: "Dia da Abolição da Escravidão dos Índios - 1680")
Celebration.create(day: 1, month: 4, description: "Dia do Tomate")
Celebration.create(day: 2, month: 4, description: "Dia do Propagandista")
Celebration.create(day: 2, month: 4, description: "Aniversário da Cidade de Suzano")
Celebration.create(day: 4, month: 4, description: "Dia Nacional do Parkinsoniano")
Celebration.create(day: 7, month: 4, description: "Dia do Corretor")
Celebration.create(day: 7, month: 4, description: "Dia do Jornalismo")
Celebration.create(day: 7, month: 4, description: "Dia do Médico Legista")
Celebration.create(day: 7, month: 4, description: "Dia Mundial da Saúde")
Celebration.create(day: 8, month: 4, description: "Dia da Natação")
Celebration.create(day: 8, month: 4, description: "Dia do Correio")
Celebration.create(day: 8, month: 4, description: "Dia Mundial do Combate ao Câncer")
Celebration.create(day: 8, month: 4, description: "Domingo de Páscoa (data móvel)")
Celebration.create(day: 9, month: 4, description: "Dia Nacional do Aço")
Celebration.create(day: 10, month: 4, description: "Dia da Engenharia e Nascimento do Bruno Ponte")
Celebration.create(day: 12, month: 4, description: "Dia do Obstetra")
Celebration.create(day: 13, month: 4, description: "Dia do Office-Boy")
Celebration.create(day: 13, month: 4, description: "Dia do Beijo")
Celebration.create(day: 13, month: 4, description: "Dia dos Jovens")
Celebration.create(day: 13, month: 4, description: "Dia do Hino Nacional -1º Execução do Hino Nacional Brasileiro -1831")
Celebration.create(day: 14, month: 4, description: "Aniversário do Santos Futebol Clube (SFC)")
Celebration.create(day: 14, month: 4, description: "Dia Pan-Americano")
Celebration.create(day: 14, month: 4, description: "Dia Mundial do Café")
Celebration.create(day: 15, month: 4, description: "Dia da Conservação do Solo")
Celebration.create(day: 15, month: 4, description: "Dia Mundial do Desenhista")
Celebration.create(day: 15, month: 4, description: "Dia do Desarmamento Infantil")
Celebration.create(day: 16, month: 4, description: "Aniversário do Alan ATR")
Celebration.create(day: 16, month: 4, description: "Dia da Voz")
Celebration.create(day: 18, month: 4, description: "Dia do Thales Lazarotto Alves")
Celebration.create(day: 18, month: 4, description: "Dia do Amigo")
Celebration.create(day: 18, month: 4, description: "Dia Nacional do Livro Infantil")
Celebration.create(day: 18, month: 4, description: "Dia de Monteiro Lobato")
Celebration.create(day: 18, month: 4, description: "Dia da Imigração Japonesa")
Celebration.create(day: 19, month: 4, description: "Dia do Índio")
Celebration.create(day: 19, month: 4, description: "Dia do Exército Brasileiro")
Celebration.create(day: 19, month: 4, description: "Dia do Psicomotricista")
Celebration.create(day: 20, month: 4, description: "Dia do Diplomata")
Celebration.create(day: 20, month: 4, description: "Dia do Disco")
Celebration.create(day: 21, month: 4, description: "Tiradentes")
Celebration.create(day: 21, month: 4, description: "Dia da Latinidade")
Celebration.create(day: 21, month: 4, description: "Dia do Metalúrgico")
Celebration.create(day: 21, month: 4, description: "Dia do Policial Civil")
Celebration.create(day: 22, month: 4, description: "Comemoração do Descobrimento do Brasil")
Celebration.create(day: 22, month: 4, description: "Dia da Força Aérea Brasileira")
Celebration.create(day: 22, month: 4, description: "Dia da Comunidade Luso-brasileira")
Celebration.create(day: 22, month: 4, description: "Dia do Planeta Terra")
Celebration.create(day: 23, month: 4, description: "Dia Mundial do Escoteiro")
Celebration.create(day: 23, month: 4, description: "Dia Mundial do Livro e do Direito do Autor")
Celebration.create(day: 24, month: 4, description: "Dia do Agente de Viagem")
Celebration.create(day: 24, month: 4, description: "Dia Internacional do Jovem Trabalhador")
Celebration.create(day: 25, month: 4, description: "Dia do Contabilista")
Celebration.create(day: 25, month: 4, description: "Dia Latino americano da Mulher Negra")
Celebration.create(day: 26, month: 4, description: "Dia do Goleiro")
Celebration.create(day: 26, month: 4, description: "Dia da 1ª Missa no Brasil")
Celebration.create(day: 27, month: 4, description: "Dia da Empregada Doméstica")
Celebration.create(day: 27, month: 4, description: "Dia do Sacerdote")
Celebration.create(day: 28, month: 4, description: "Dia da Educação")
Celebration.create(day: 28, month: 4, description: "Dia da Sogra")
Celebration.create(day: 29, month: 4, description: "Dia Internacional da Dança")
Celebration.create(day: 30, month: 4, description: "Dia do Ferroviário")
Celebration.create(day: 30, month: 4, description: "Dia Nacional da Mulher")

Celebration.create(day: 1, month: 5, description: "Dia Mundial do Trabalho")
Celebration.create(day: 2, month: 5, description: "Dia Nacional do Ex-combatente")
Celebration.create(day: 3, month: 5, description: "Dia do Taquígrafo")
Celebration.create(day: 3, month: 5, description: "Dia do Sol")
Celebration.create(day: 3, month: 5, description: "Dia do Sertanejo")
Celebration.create(day: 5, month: 5, description: "Dia do aniversario da cidade de Garça-SP")
Celebration.create(day: 5, month: 5, description: "Dia de Marechal Rondon")
Celebration.create(day: 5, month: 5, description: "Dia da Comunidade")
Celebration.create(day: 5, month: 5, description: "Dia Nacional do Expedicionário")
Celebration.create(day: 5, month: 5, description: "Dia do Pintor")
Celebration.create(day: 5, month: 5, description: "Dia do Marechal Rondon")
Celebration.create(day: 6, month: 5, description: "Dia do Cartógrafo")
Celebration.create(day: 6, month: 5, description: "Dia da Matemática")
Celebration.create(day: 7, month: 5, description: "Dia do Oftalmologista")
Celebration.create(day: 7, month: 5, description: "Dia do Silêncio")
Celebration.create(day: 8, month: 5, description: "Dia da Vitória")
Celebration.create(day: 8, month: 5, description: "Dia do Profissional de Marketing")
Celebration.create(day: 8, month: 5, description: "Dia do Artista Plástico")
Celebration.create(day: 8, month: 5, description: "Dia Internacional da Cruz Vermelha")
Celebration.create(day: 9, month: 5, description: "Dia da Europa")
Celebration.create(day: 9, month: 5, description: "Aniversário da cidade de Teixeira de Freitas - Ba")
Celebration.create(day: 10, month: 5, description: "Dia da Cavalaria")
Celebration.create(day: 10, month: 5, description: "Dia do Guia de Turismo")
Celebration.create(day: 10, month: 5, description: "Dia do Campo")
Celebration.create(day: 11, month: 5, description: "Dia da Integração do Telégrafo no Brasil")
Celebration.create(day: 12, month: 5, description: "Dia Mundial do Enfermeiro")
Celebration.create(day: 13, month: 5, description: "Comemoração da Abolição da Escravatura")
Celebration.create(day: 13, month: 5, description: "Dia da Fraternidade Brasileira")
Celebration.create(day: 13, month: 5, description: "Dia do Automóvel")
Celebration.create(day: 13, month: 5, description: "Dia das Mães (Variável: Segundo domingo de maio)")
Celebration.create(day: 14, month: 5, description: "Dia Continental do Seguro")
Celebration.create(day: 15, month: 5, description: "Dia do Assistente Social")
Celebration.create(day: 15, month: 5, description: "Dia do Gerente Bancário")
Celebration.create(day: 16, month: 5, description: "Dia do Gari")
Celebration.create(day: 17, month: 5, description: "Dia Internacional da Comunicação e das Telecomunicações")
Celebration.create(day: 17, month: 5, description: "Dia da Constituição")
Celebration.create(day: 18, month: 5, description: "Dia dos Vidraceiros")
Celebration.create(day: 18, month: 5, description: "Dia Internacional dos Museus")
Celebration.create(day: 19, month: 5, description: "Dia dos Acadêmicos de Direito")
Celebration.create(day: 20, month: 5, description: "Dia do Comissário de Menores")
Celebration.create(day: 21, month: 5, description: "Dia da Língua Nacional")
Celebration.create(day: 22, month: 5, description: "Dia do Apicultor")
Celebration.create(day: 22, month: 5, description: "Dia do Abraço")
Celebration.create(day: 23, month: 5, description: "Dia da Juventude Constitucionalista")
Celebration.create(day: 24, month: 5, description: "Dia da Infantaria")
Celebration.create(day: 24, month: 5, description: "Dia do Datilógrafo")
Celebration.create(day: 24, month: 5, description: "Dia do Detento")
Celebration.create(day: 24, month: 5, description: "Dia do Telegrafista")
Celebration.create(day: 24, month: 5, description: "Dia do Vestibulando")
Celebration.create(day: 25, month: 5, description: "Dia da Indústria")
Celebration.create(day: 25, month: 5, description: "Dia do Massagista")
Celebration.create(day: 25, month: 5, description: "Dia do Trabalhador Rural")
Celebration.create(day: 27, month: 5, description: "Dia do Profissional Liberal")
Celebration.create(day: 27, month: 5, description: "Dia do Engenheiro Agrônomo")
Celebration.create(day: 28, month: 5, description: "Dia Internacional de ação da saúde da Mulher e combate da mortalidade materna")
Celebration.create(day: 29, month: 5, description: "Dia do Chaveiro")
Celebration.create(day: 29, month: 5, description: "Dia do Estatístico")
Celebration.create(day: 29, month: 5, description: "Dia do Geógrafo")
Celebration.create(day: 30, month: 5, description: "Dia do Geólogo")
Celebration.create(day: 30, month: 5, description: "Dia das Bandeiras")
Celebration.create(day: 31, month: 5, description: "Dia do Comissário de Bordo")
Celebration.create(day: 31, month: 5, description: "Dia Mundial das Comunicações Sociais")
Celebration.create(day: 31, month: 5, description: "Dia do Espírito Santo")

Celebration.create(day: 1, month: 6, description: "Semana Mundial do Meio Ambiente")
Celebration.create(day: 1, month: 6, description: "Aniversário do municipio de Brasnorte MT")
Celebration.create(day: 1, month: 6, description: "Aniversário de Ines Rodrigues da Silva Souza")
Celebration.create(day: 1, month: 6, description: "Aniversário de Caxias do Sul")
Celebration.create(day: 1, month: 6, description: "Primeira transmissão de TV no Brasil")
Celebration.create(day: 3, month: 6, description: "Dia Mundial do Administrador de Pessoal")
Celebration.create(day: 3, month: 6, description: "Pentecostes (festa móvel)")
Celebration.create(day: 5, month: 6, description: "Dia da Ecologia")
Celebration.create(day: 5, month: 6, description: "Dia Mundial do Meio Ambiente")
Celebration.create(day: 7, month: 6, description: "Dia da Liberdade de Imprensa")
Celebration.create(day: 8, month: 6, description: "Dia do Citricultor")
Celebration.create(day: 9, month: 6, description: "Dia do Tenista")
Celebration.create(day: 9, month: 6, description: "Dia da Imunização")
Celebration.create(day: 9, month: 6, description: "Dia Nacional de Anchieta")
Celebration.create(day: 10, month: 6, description: "Dia da Artilharia")
Celebration.create(day: 10, month: 6, description: "Dia da Língua Portuguesa")
Celebration.create(day: 10, month: 6, description: "Dia da Raça")
Celebration.create(day: 11, month: 6, description: "Dia da Marinha Brasileira")
Celebration.create(day: 11, month: 6, description: "Dia do Educador Sanitário")
Celebration.create(day: 12, month: 6, description: "Dia do Correio Aéreo Nacional")
Celebration.create(day: 12, month: 6, description: "Dia dos Namorados")
Celebration.create(day: 13, month: 6, description: "Dia de Santo Antônio")
Celebration.create(day: 13, month: 6, description: "Dia do Turista")
Celebration.create(day: 14, month: 6, description: "Dia do Solista")
Celebration.create(day: 17, month: 6, description: "Dia do Funcionário Público Aposentado")
Celebration.create(day: 18, month: 6, description: "Dia da Assembléia de Deus")
Celebration.create(day: 18, month: 6, description: "Dia do Químico")
Celebration.create(day: 18, month: 6, description: "Dia da Imigração Japonesa")
Celebration.create(day: 19, month: 6, description: "Dia do Cinema Brasileiro")
Celebration.create(day: 20, month: 6, description: "Dia do Revendedor")
Celebration.create(day: 21, month: 6, description: "Dia da Mídia")
Celebration.create(day: 21, month: 6, description: "Dia do Imigrante")
Celebration.create(day: 21, month: 6, description: "Início do inverno")
Celebration.create(day: 23, month: 6, description: "Corpus Christi")
Celebration.create(day: 23, month: 6, description: "Dia Universal Olímpico")
Celebration.create(day: 24, month: 6, description: "Dia das Empresas Gráficas")
Celebration.create(day: 24, month: 6, description: "Dia de São João")
Celebration.create(day: 24, month: 6, description: "Dia Internacional do Leite")
Celebration.create(day: 25, month: 6, description: "Dia da Morte de Michael Jackson")
Celebration.create(day: 26, month: 6, description: "Dia do Metrologista")
Celebration.create(day: 27, month: 6, description: "Dia Nacional do Progresso")
Celebration.create(day: 28, month: 6, description: "Dia da Renovação Espiritual")
Celebration.create(day: 29, month: 6, description: "Dia do Papa")
Celebration.create(day: 29, month: 6, description: "Dia da Telefonista")
Celebration.create(day: 29, month: 6, description: "Dia do Pescador")
Celebration.create(day: 29, month: 6, description: "Dia de São Pedro")
Celebration.create(day: 30, month: 6, description: "Dia Nacional do Bumba-Meu-Boi")

Celebration.create(day: 1, month: 7, description: "Dia da Vacina BCG")
Celebration.create(day: 2, month: 7, description: "Independência da Bahia")
Celebration.create(day: 2, month: 7, description: "Dia do Hospital")
Celebration.create(day: 2, month: 7, description: "Dia do Bombeiro Brasileiro")
Celebration.create(day: 4, month: 7, description: "Dia Internacional do Cooperativismo")
Celebration.create(day: 4, month: 7, description: "Comemoração da Independência dos EUA (Data Nacional)")
Celebration.create(day: 4, month: 7, description: "Dia do Operador de Telemarketing")
Celebration.create(day: 6, month: 7, description: "Dia da Criação do IBGE")
Celebration.create(day: 7, month: 7, description: "Dia do Mendes")
Celebration.create(day: 8, month: 7, description: "dia mundial da alegria")
Celebration.create(day: 8, month: 7, description: "Dia do Panificador")
Celebration.create(day: 9, month: 7, description: "Dia da Revolução e do Soldado Constitucionalista")
Celebration.create(day: 10, month: 7, description: "Dia da Pizza")
Celebration.create(day: 12, month: 7, description: "Dia do Engenheiro Florestal")
Celebration.create(day: 13, month: 7, description: "Dia do Engenheiro de Saneamento")
Celebration.create(day: 13, month: 7, description: "Dia do Cantor")
Celebration.create(day: 13, month: 7, description: "Dia Mundial do Rock")
Celebration.create(day: 14, month: 7, description: "Dia do Propagandista de Laboratório")
Celebration.create(day: 14, month: 7, description: "Dia do Engenheiro Aqüicultor")
Celebration.create(day: 14, month: 7, description: "Dia da Liberdade de Pensamento")
Celebration.create(day: 15, month: 7, description: "Dia Nacional dos Clubes")
Celebration.create(day: 15, month: 7, description: "Dia do Homem (no Brasil)")
Celebration.create(day: 16, month: 7, description: "Dia do Comerciante")
Celebration.create(day: 17, month: 7, description: "Dia de Proteção às Florestas")
Celebration.create(day: 19, month: 7, description: "Dia da Caridade")
Celebration.create(day: 19, month: 7, description: "Dia Nacional do Futebol")
Celebration.create(day: 20, month: 7, description: "Dia do Amigo e Internacional da Amizade")
Celebration.create(day: 20, month: 7, description: "Dia da Primeira Viagem à Lua (1969)")
Celebration.create(day: 23, month: 7, description: "Dia do Guarda Rodoviário")
Celebration.create(day: 25, month: 7, description: "Dia de São Cristóvão")
Celebration.create(day: 25, month: 7, description: "Dia do Colono")
Celebration.create(day: 25, month: 7, description: "Dia do Escritor")
Celebration.create(day: 25, month: 7, description: "Dia do Motorista")
Celebration.create(day: 25, month: 7, description: "Dia da Mulher Afro latino americana e Caribenha")
Celebration.create(day: 25, month: 7, description: "Dia da Trabalhadora rural")
Celebration.create(day: 26, month: 7, description: "Dia dos avós")
Celebration.create(day: 27, month: 7, description: "Aniversário de Jardinópolis - SP")
Celebration.create(day: 27, month: 7, description: "Dia do Motociclista")
Celebration.create(day: 28, month: 7, description: "Dia do Agricultor")
Celebration.create(day: 30, month: 7, description: "Aniversário de Santana do Livramento -RS")

Celebration.create(day: 1, month: 8, description: "Dia Nacional do Selo")
Celebration.create(day: 1, month: 8, description: "Dia Mundial da Amamentação")
Celebration.create(day: 3, month: 8, description: "Dia do Renascimento da LUA (Milena)")
Celebration.create(day: 3, month: 8, description: "Dia do Tintureiro")
Celebration.create(day: 4, month: 8, description: "Dia do Padre")
Celebration.create(day: 5, month: 8, description: "Dia Nacional da Saúde")
Celebration.create(day: 7, month: 8, description: "Sanção da Lei Maria da Penha (11.340/6)")
Celebration.create(day: 11, month: 8, description: "Dia da Televisão")
Celebration.create(day: 11, month: 8, description: "Dia do Advogado")
Celebration.create(day: 11, month: 8, description: "Dia do Estudante")
Celebration.create(day: 11, month: 8, description: "Dia do Garçom")
Celebration.create(day: 11, month: 8, description: "Dia Internacional da Logosofia")
Celebration.create(day: 12, month: 8, description: "Dia Nacional da Artes")
Celebration.create(day: 12, month: 8, description: "Dia da luta contra violência no campo - Marcha das Margaridas")
Celebration.create(day: 12, month: 8, description: "Dia dos Pais (festa móvel - 2º domingo de agosto)")
Celebration.create(day: 13, month: 8, description: "Dia do Canhoto")
Celebration.create(day: 13, month: 8, description: "Dia do Economista")
Celebration.create(day: 13, month: 8, description: "Dia dos Encarcerados")
Celebration.create(day: 13, month: 8, description: "Dia do Pensamento")
Celebration.create(day: 14, month: 8, description: "Dia da Unidade Humana")
Celebration.create(day: 14, month: 8, description: "Dia do Controle da Poluição Industrial")
Celebration.create(day: 14, month: 8, description: "Morte do educador Alceu Amoroso Lima (1983)")
Celebration.create(day: 15, month: 8, description: "Assunção de Nossa Senhora")
Celebration.create(day: 15, month: 8, description: "Dia de São Tarcísio - martir da Eucaristia")
Celebration.create(day: 15, month: 8, description: "Dia do Coroinha, Acólito e Cerimoniário")
Celebration.create(day: 15, month: 8, description: "Dia da Informática")
Celebration.create(day: 15, month: 8, description: "Dia dos Solteiros")
Celebration.create(day: 16, month: 8, description: "Aniversário de Teresina (Capital do Piaui, fundada em 1852)")
Celebration.create(day: 16, month: 8, description: "Dia do Filósofo")
Celebration.create(day: 19, month: 8, description: "Dia do Artista de Teatro")
Celebration.create(day: 19, month: 8, description: "Dia Mundial da Fotografia")
Celebration.create(day: 20, month: 8, description: "Dia dos Maçons")
Celebration.create(day: 20, month: 8, description: "Dia do Amigo")
Celebration.create(day: 22, month: 8, description: "Dia do Folclore")
Celebration.create(day: 23, month: 8, description: "Dia da Injustiça")
Celebration.create(day: 24, month: 8, description: "Dia da Infância")
Celebration.create(day: 24, month: 8, description: "Dia dos Artistas")
Celebration.create(day: 24, month: 8, description: "Dia de São Bartolomeu")
Celebration.create(day: 25, month: 8, description: "Dia do Feirante")
Celebration.create(day: 25, month: 8, description: "Dia do Soldado")
Celebration.create(day: 26, month: 8, description: "Dia dos avôs e avós")
Celebration.create(day: 27, month: 8, description: "Dia do Corretor de Imóveis")
Celebration.create(day: 27, month: 8, description: "Dia do Psicólogo")
Celebration.create(day: 28, month: 8, description: "Dia da Avicultura")
Celebration.create(day: 28, month: 8, description: "Dia dos Bancários")
Celebration.create(day: 28, month: 8, description: "Dia Nacional do Voluntário")
Celebration.create(day: 29, month: 8, description: "Dia Nacional de Combate ao Fumo")
Celebration.create(day: 31, month: 8, description: "Dia dos Nutricionistas")

Celebration.create(day: 1, month: 9, description: "Dia do Bailarino(a)")
Celebration.create(day: 1, month: 9, description: "Aniversário da cidade de Mogi das Cruzes")
Celebration.create(day: 1, month: 9, description: "Início da Semana da Pátria")
Celebration.create(day: 1, month: 9, description: "Dia do Professor de Educação Física")
Celebration.create(day: 2, month: 9, description: "Dia do Repórter Fotográfico")
Celebration.create(day: 3, month: 9, description: "Dia do Guarda Civil")
Celebration.create(day: 3, month: 9, description: "Dia do Biólogo")
Celebration.create(day: 4, month: 9, description: "Dia de Santa Rosália")
Celebration.create(day: 5, month: 9, description: "Dia Nacional Jéssika Luiza Oliveira Sampaio")
Celebration.create(day: 5, month: 9, description: "Dia Oficial da Farmácia")
Celebration.create(day: 5, month: 9, description: "Dia da Amazônia")
Celebration.create(day: 6, month: 9, description: "Dia do Alfaiate")
Celebration.create(day: 6, month: 9, description: "Dia Internacional de ação pela igualdade da Mulher")
Celebration.create(day: 6, month: 9, description: "Oficialização da Letra do Hino Nacional")
Celebration.create(day: 7, month: 9, description: "Independência do Brasil - Data Nacional")
Celebration.create(day: 7, month: 9, description: "Dia Internacional da Cretina")
Celebration.create(day: 8, month: 9, description: "Aniversário de São Luís do Maranhão")
Celebration.create(day: 8, month: 9, description: "Dia Internacional da Alfabetização")
Celebration.create(day: 9, month: 9, description: "Dia do Administrador")
Celebration.create(day: 9, month: 9, description: "Dia do Médico Veterinário")
Celebration.create(day: 9, month: 9, description: "Dia da Velocidade")
Celebration.create(day: 10, month: 9, description: "Dia da Imprensa")
Celebration.create(day: 10, month: 9, description: "Fundação do 1º Jornal no Brasil")
Celebration.create(day: 12, month: 9, description: "Dia do Operador de Rastreamento e dia do Físico")
Celebration.create(day: 13, month: 9, description: "Dia do Agrônomo")
Celebration.create(day: 13, month: 9, description: "Dia do Programador")
Celebration.create(day: 14, month: 9, description: "Dia da Cruz")
Celebration.create(day: 14, month: 9, description: "Dia do Frevo")
Celebration.create(day: 14, month: 9, description: "Dia latino americano da imagem da mulher nos meios de Comunicação")
Celebration.create(day: 15, month: 9, description: "Dia do Cliente")
Celebration.create(day: 16, month: 9, description: "Dia Internacional para a Preservação da Camada de Ozônio")
Celebration.create(day: 17, month: 9, description: "Dia da Compreensão Mundial")
Celebration.create(day: 18, month: 9, description: "Dia dos Símbolos Nacionais")
Celebration.create(day: 19, month: 9, description: "Dia de São Geraldo")
Celebration.create(day: 19, month: 9, description: "Dia do Teatro")
Celebration.create(day: 19, month: 9, description: "Dia do Comprador")
Celebration.create(day: 20, month: 9, description: "Dia do Funcionário Municipal")
Celebration.create(day: 20, month: 9, description: "Dia do Gaúcho")
Celebration.create(day: 20, month: 9, description: "Dia da Revolução Farroupilha (RS)")
Celebration.create(day: 20, month: 9, description: "Dia do Engenheiro Químico")
Celebration.create(day: 21, month: 9, description: "Dia da Árvore")
Celebration.create(day: 21, month: 9, description: "Dia do Fazendeiro")
Celebration.create(day: 21, month: 9, description: "Dia do Radialista")
Celebration.create(day: 21, month: 9, description: "Dia do Contra")
Celebration.create(day: 21, month: 9, description: "Dia da Luta Nacional das Pessoas com Deficiências")
Celebration.create(day: 21, month: 9, description: "Aniversário da cidade de São Mateus ES")
Celebration.create(day: 22, month: 9, description: "Dia da Banana")
Celebration.create(day: 22, month: 9, description: "Dia dos Amantes")
Celebration.create(day: 22, month: 9, description: "Data da Juventude do Brasil")
Celebration.create(day: 22, month: 9, description: "Dia do Contador")
Celebration.create(day: 22, month: 9, description: "Dia de São Mateus")
Celebration.create(day: 23, month: 9, description: "Dia do técnico industrial")
Celebration.create(day: 23, month: 9, description: "Dia Internacional contra a exploração sexual e o tráfico de mulheres e crianças")
Celebration.create(day: 23, month: 9, description: "Início da Primavera")
Celebration.create(day: 23, month: 9, description: "Dia do Soldador")
Celebration.create(day: 25, month: 9, description: "Dia Nacional do Trânsito")
Celebration.create(day: 26, month: 9, description: "Dia Interamericano das Relações Públicas")
Celebration.create(day: 26, month: 9, description: "Dia Mundial do Coração")
Celebration.create(day: 26, month: 9, description: "Dia Nacional do Surdo")
Celebration.create(day: 27, month: 9, description: "Dia do Encanador")
Celebration.create(day: 27, month: 9, description: "Dia Mundial de Turismo")
Celebration.create(day: 28, month: 9, description: "Dia da Lei do Ventre Livre")
Celebration.create(day: 28, month: 9, description: "Dia da luta pela discriminalização do aborto na América Latina e Caribe")
Celebration.create(day: 29, month: 9, description: "Dia do Anunciante")
Celebration.create(day: 29, month: 9, description: "Aprovação da Lei que garante quotas para as Mulheres na Política (Lei 9.10/95)")
Celebration.create(day: 29, month: 9, description: "Dia Mundial do Coração")
Celebration.create(day: 29, month: 9, description: "Dia do Petróleo")
Celebration.create(day: 30, month: 9, description: "Dia da Secretária")
Celebration.create(day: 30, month: 9, description: "Dia da Navegação")
Celebration.create(day: 30, month: 9, description: "Dia Mundial do Tradutor")
Celebration.create(day: 30, month: 9, description: "Dia Nacional do Jornaleiro")

Celebration.create(day: 1, month: 10, description: "Dia Internacional da Terceira Idade")
Celebration.create(day: 1, month: 10, description: "Dia do Vendedor")
Celebration.create(day: 1, month: 10, description: "Dia Nacional do Vereador")
Celebration.create(day: 3, month: 10, description: "Dia Mundial do Dentista")
Celebration.create(day: 3, month: 10, description: "Dia do Petróleo Brasileiro")
Celebration.create(day: 3, month: 10, description: "Dia das Abelhas")
Celebration.create(day: 4, month: 10, description: "Dia Mundial dos Animais")
Celebration.create(day: 4, month: 10, description: "Dia da Natureza")
Celebration.create(day: 4, month: 10, description: "Dia da Ecologia")
Celebration.create(day: 4, month: 10, description: "Dia do Barman")
Celebration.create(day: 4, month: 10, description: "Dia do Cão")
Celebration.create(day: 4, month: 10, description: "Dia de São Francisco de Assis")
Celebration.create(day: 4, month: 10, description: "Dia do Agente de Saúde e do Agente de Endemias")
Celebration.create(day: 5, month: 10, description: "Dia das Aves")
Celebration.create(day: 7, month: 10, description: "Dia do Compositor")
Celebration.create(day: 8, month: 10, description: "Dia do Nascituro")
Celebration.create(day: 8, month: 10, description: "Dia do Direito à Vida")
Celebration.create(day: 8, month: 10, description: "Dia do Nordestino")
Celebration.create(day: 10, month: 10, description: "Dia nacional de luta contra a violência à Mulher")
Celebration.create(day: 10, month: 10, description: "Semana da Ciência e Tecnologia")
Celebration.create(day: 11, month: 10, description: "Dia do Deficiente Físico")
Celebration.create(day: 11, month: 10, description: "Criação de Mato Grosso do Sul")
Celebration.create(day: 11, month: 10, description: "Dia do Teatro Municipal")
Celebration.create(day: 12, month: 10, description: "Dia internacional da mulher Indígena")
Celebration.create(day: 12, month: 10, description: "Dia de Nossa Senhora Aparecida")
Celebration.create(day: 12, month: 10, description: "Dia da Criança")
Celebration.create(day: 12, month: 10, description: "Dia Nacional da Leitura")
Celebration.create(day: 12, month: 10, description: "Dia do Atletismo")
Celebration.create(day: 12, month: 10, description: "Dia do Engenheiro Agrônomo")
Celebration.create(day: 12, month: 10, description: "Dia do Mar")
Celebration.create(day: 12, month: 10, description: "Dia do Descobrimento da América")
Celebration.create(day: 13, month: 10, description: "Dia do Terapeuta Ocupacional")
Celebration.create(day: 13, month: 10, description: "Dia do Fisioterapeuta")
Celebration.create(day: 14, month: 10, description: "Dia Nacional da Pecuária")
Celebration.create(day: 15, month: 10, description: "Dia Mundial da Mulher Rural")
Celebration.create(day: 15, month: 10, description: "Dia da/o Normalista")
Celebration.create(day: 15, month: 10, description: "Dia do Professor")
Celebration.create(day: 16, month: 10, description: "Dia Mundial da Alimentação")
Celebration.create(day: 16, month: 10, description: "Dia da Ciência e Tecnologia")
Celebration.create(day: 17, month: 10, description: "Dia da Indústria Aeronáutica Brasileira")
Celebration.create(day: 17, month: 10, description: "Dia do Eletricista")
Celebration.create(day: 18, month: 10, description: "Dia do Médico")
Celebration.create(day: 18, month: 10, description: "Dia do Estivador")
Celebration.create(day: 18, month: 10, description: "Dia do Securitário")
Celebration.create(day: 18, month: 10, description: "Dia do Pintor")
Celebration.create(day: 19, month: 10, description: "Dia do Piauí")
Celebration.create(day: 19, month: 10, description: "Dia do Profissional da Informática")
Celebration.create(day: 20, month: 10, description: "Dia Internacional do Controlador de Tráfego Aéreo")
Celebration.create(day: 20, month: 10, description: "Dia do Arquivista")
Celebration.create(day: 20, month: 10, description: "Dia do Adolecente")
Celebration.create(day: 20, month: 10, description: "Dia do Poeta")
Celebration.create(day: 21, month: 10, description: "Dia do Contato")
Celebration.create(day: 23, month: 10, description: "Dia do Aviador e da Força Aérea Brasileira")
Celebration.create(day: 24, month: 10, description: "Dia das Nações Unidas – ONU")
Celebration.create(day: 24, month: 10, description: "Aniversário de Goiânia")
Celebration.create(day: 25, month: 10, description: "Dia da Democracia")
Celebration.create(day: 25, month: 10, description: "Dia da Saúde Dentária")
Celebration.create(day: 25, month: 10, description: "Dia do Dentista Brasileiro")
Celebration.create(day: 25, month: 10, description: "Dia do Sapateiro")
Celebration.create(day: 28, month: 10, description: "Dia do Funcionário Público")
Celebration.create(day: 28, month: 10, description: "Dia do Hidrógrafo")
Celebration.create(day: 29, month: 10, description: "Dia Nacional do Livro")
Celebration.create(day: 29, month: 10, description: "Dia Nacional do Adolescente")
Celebration.create(day: 30, month: 10, description: "Dia do Comerciário")
Celebration.create(day: 31, month: 10, description: "Dia das BruxasHalloween")
Celebration.create(day: 31, month: 10, description: "Dia Mundial do Comissário de Vôo")
Celebration.create(day: 31, month: 10, description: "Dia nacional do Saci")
Celebration.create(day: 31, month: 10, description: "Dia do Balconista")
Celebration.create(day: 31, month: 10, description: "Dia da Reforma Protestante")

Celebration.create(day: 1, month: 11, description: "Dia de Todos os Santos")
Celebration.create(day: 2, month: 11, description: "Dia de Finados")
Celebration.create(day: 3, month: 11, description: "Dia do Cabeleireiro")
Celebration.create(day: 3, month: 11, description: "Instituição do Direito e Voto da Mulher (1930)")
Celebration.create(day: 3, month: 11, description: "Dia Internacional do Gerenciamento de Projetos")
Celebration.create(day: 4, month: 11, description: "Dia do Inventor")
Celebration.create(day: 5, month: 11, description: "Dia da Ciência e Cultura")
Celebration.create(day: 5, month: 11, description: "Dia do Cinema Brasileiro")
Celebration.create(day: 5, month: 11, description: "Dia Nacional do Design")
Celebration.create(day: 5, month: 11, description: "Dia Nacional da Língua Portuguesa")
Celebration.create(day: 5, month: 11, description: "Dia do Radioamador e Técnico em Eletrônica")
Celebration.create(day: 5, month: 11, description: "Dia do Técnico Agrícola")
Celebration.create(day: 7, month: 11, description: "Dia do Radialista")
Celebration.create(day: 8, month: 11, description: "Dia do Aposentado")
Celebration.create(day: 8, month: 11, description: "Dia Mundial do Urbanismo")
Celebration.create(day: 9, month: 11, description: "Dia do Hoteleiro")
Celebration.create(day: 10, month: 11, description: "Dia da Mriana Paz Guimarães")
Celebration.create(day: 10, month: 11, description: "Dia do Trigo")
Celebration.create(day: 11, month: 11, description: "Dia do Soldado Desconhecido")
Celebration.create(day: 12, month: 11, description: "Dia do Diretor de Escola")
Celebration.create(day: 12, month: 11, description: "Dia do Supermercado")
Celebration.create(day: 14, month: 11, description: "Dia Nacional da Alfabetização")
Celebration.create(day: 15, month: 11, description: "Proclamação da República")
Celebration.create(day: 16, month: 11, description: "Semana da Música")
Celebration.create(day: 17, month: 11, description: "Dia da Criatividade")
Celebration.create(day: 19, month: 11, description: "Dia Internacional do Homem")
Celebration.create(day: 19, month: 11, description: "Dia da Bandeira")
Celebration.create(day: 20, month: 11, description: "Dia do Auditor Interno")
Celebration.create(day: 20, month: 11, description: "Dia do Biomédico")
Celebration.create(day: 20, month: 11, description: "Dia Nacional da Consciência Negra")
Celebration.create(day: 21, month: 11, description: "Dia da Homeopatia")
Celebration.create(day: 21, month: 11, description: "Dia mundial da televisão")
Celebration.create(day: 21, month: 11, description: "Dia das Saudações")
Celebration.create(day: 22, month: 11, description: "Dia do Músico")
Celebration.create(day: 22, month: 11, description: "Dia Internacional do Livro")
Celebration.create(day: 23, month: 11, description: "Dia do Engenheiro Eletricista")
Celebration.create(day: 25, month: 11, description: "Dia Nacional do Doador de Sangue")
Celebration.create(day: 26, month: 11, description: "Dia do Ministério Público")
Celebration.create(day: 27, month: 11, description: "Dia do Técnico da Segurança do Trabalho")
Celebration.create(day: 28, month: 11, description: "Dia Mundial de Ação de Graças")
Celebration.create(day: 28, month: 11, description: "Dia do aniversário de Franca-SP")

Celebration.create(day: 1, month: 12, description: "Dia Internacional da Luta Contra a AIDS")
Celebration.create(day: 1, month: 12, description: "Dia do Imigrante")
Celebration.create(day: 1, month: 12, description: "Dia do Numismata")
Celebration.create(day: 2, month: 12, description: "Dia Nacional do Samba")
Celebration.create(day: 2, month: 12, description: "Dia da Astronomia")
Celebration.create(day: 2, month: 12, description: "Dia Pan-americano da Saúde")
Celebration.create(day: 2, month: 12, description: "Dia Nacional das Relações Públicas")
Celebration.create(day: 3, month: 12, description: "Dia Internacional do Portador de Deficiência")
Celebration.create(day: 4, month: 12, description: "Dia da Propaganda")
Celebration.create(day: 4, month: 12, description: "Dia do Pedicuro")
Celebration.create(day: 4, month: 12, description: "Dia do Orientador Educacional")
Celebration.create(day: 8, month: 12, description: "Dia Mundial da Imaculada Conceição")
Celebration.create(day: 8, month: 12, description: "Dia da Família")
Celebration.create(day: 8, month: 12, description: "Dia da Justiça")
Celebration.create(day: 9, month: 12, description: "Dia do Fonoaudiólogo")
Celebration.create(day: 9, month: 12, description: "Dia do Alcoólico Recuperado")
Celebration.create(day: 10, month: 12, description: "Declaração Universal Direitos Humanos")
Celebration.create(day: 10, month: 12, description: "Dia Internacional dos Povos Indígenas")
Celebration.create(day: 10, month: 12, description: "Dia Universal do Palhaço")
Celebration.create(day: 11, month: 12, description: "Dia do Arquiteto")
Celebration.create(day: 11, month: 12, description: "Dia do Engenheiro")
Celebration.create(day: 11, month: 12, description: "Dia do Agrônonimo")
Celebration.create(day: 12, month: 12, description: "Dia da Babilônia")
Celebration.create(day: 13, month: 12, description: "Dia do Cego")
Celebration.create(day: 13, month: 12, description: "Dia do Marinheiro")
Celebration.create(day: 13, month: 12, description: "Dia do Óptico")
Celebration.create(day: 13, month: 12, description: "Dia de Santa Luzia")
Celebration.create(day: 13, month: 12, description: "Dia do Engenheiro Avaliador e Perito de Engenharia")
Celebration.create(day: 13, month: 12, description: "Dia do Pedreiro")
Celebration.create(day: 14, month: 12, description: "Dia Nacional do Ministério Público")
Celebration.create(day: 15, month: 12, description: "Dia Nacional da Economia Solidária")
Celebration.create(day: 16, month: 12, description: "Dia do Reservista")
Celebration.create(day: 18, month: 12, description: "Dia do Museólogo")
Celebration.create(day: 19, month: 12, description: "Dia do Atleta Profissional")
Celebration.create(day: 20, month: 12, description: "Dia do Mecânico")
Celebration.create(day: 21, month: 12, description: "Dia do Atleta")
Celebration.create(day: 22, month: 12, description: "Início do verão")
Celebration.create(day: 23, month: 12, description: "Dia do Vizinho")
Celebration.create(day: 24, month: 12, description: "Dia do Órfão")
Celebration.create(day: 25, month: 12, description: "Natal")
Celebration.create(day: 26, month: 12, description: "Dia da Lembrança")
Celebration.create(day: 28, month: 12, description: "Dia do Salva-vidas")
Celebration.create(day: 31, month: 12, description: "Dia de São Silvestre")
Celebration.create(day: 31, month: 12, description: "Reveillon")

Group.create(name: 'Acessório para bebê')
Group.create(name: 'Capa celular')
Group.create(name: 'Fone de ouvido')
Group.create(name: 'Mousepad')
Group.create(name: 'Apoio notebook')
Group.create(name: 'Case notebook')
Group.create(name: 'Almofada')
Group.create(name: 'Boneca')
Group.create(name: 'Caneca')
Group.create(name: 'Copo')
Group.create(name: 'Luminária')
Group.create(name: 'Necessarie')
Group.create(name: 'Pantufa')
Group.create(name: 'Pelúcia')
Group.create(name: 'Personalizados')
Group.create(name: 'Porta chaves')
Group.create(name: 'Porta jóias')
Group.create(name: 'Porta retrato')
Group.create(name: 'Squezze')
Group.create(name: 'Travesseiro')

Tag.create(name: 'Avós')
Tag.create(name: 'Pai')
Tag.create(name: 'Mãe')
Tag.create(name: 'Filhos')
Tag.create(name: 'Irmãos')
Tag.create(name: 'Tios')
Tag.create(name: 'Sobrinhos')
Tag.create(name: 'Primos')
Tag.create(name: 'Padrinhos')
Tag.create(name: 'Afilhados')
Tag.create(name: 'Esposos')
Tag.create(name: 'Amigos')
Tag.create(name: 'Recem Nascidos')